/**/ground_vehicle_twist_odometry:
  ros__parameters:
    use_sim_time: $(var use_sim_time)
    odometry_frame: robot_odom
    base_frame: robot_base_link
    publish_tf: True
    expected_incoming_twist_msg_rate: 40.0
